const path = require("node:path");
const dotenv = require("dotenv");
const mongoose = require("mongoose");

dotenv.config({ path: path.resolve(__dirname, "..", ".env") });

const Medicine = require("../src/models/Medicine");

function expiryAfterMonths(months) {
  const date = new Date();
  date.setMonth(date.getMonth() + months);
  date.setHours(0, 0, 0, 0);
  return date;
}

const medicines = [
  {
    code: "MED-PR-001",
    name: "Paracetamol 500mg Tablet",
    category: "Pain Relief",
    description: "Analgesic and antipyretic medicine for mild to moderate pain and fever.",
    prescriptionRequired: false,
    uses: "Fever, headache, body ache",
    dosage: "1 tablet every 6-8 hours as needed (max as directed by physician)",
    sideEffects: "Nausea, rash (rare)",
    warnings: "Do not exceed recommended daily dose; caution in liver disease",
    storageInstructions: "Store below 25C in a dry place",
    manufacturer: "Sun Pharma",
    price: 25,
    stock: 220,
    lowStockThreshold: 30,
    batchNo: "PR2401",
    expiryDate: expiryAfterMonths(24),
  },
  {
    code: "MED-PR-002",
    name: "Ibuprofen 400mg Tablet",
    category: "Pain Relief",
    description: "NSAID used for pain, inflammation, and fever.",
    prescriptionRequired: false,
    uses: "Muscle pain, joint pain, fever",
    dosage: "1 tablet after food, as directed",
    sideEffects: "Acidity, stomach discomfort, nausea",
    warnings: "Avoid in active gastric ulcer and severe kidney disease",
    storageInstructions: "Store at room temperature away from moisture",
    manufacturer: "Abbott",
    price: 40,
    stock: 180,
    lowStockThreshold: 25,
    batchNo: "PR2402",
    expiryDate: expiryAfterMonths(20),
  },
  {
    code: "MED-AB-001",
    name: "Amoxicillin 500mg Capsule",
    category: "Antibiotics",
    description: "Penicillin-class antibiotic for bacterial infections.",
    prescriptionRequired: true,
    uses: "Respiratory, skin, and ENT bacterial infections",
    dosage: "As prescribed by physician",
    sideEffects: "Diarrhea, nausea, rash",
    warnings: "Complete full course; avoid if allergic to penicillins",
    storageInstructions: "Keep in original strip below 25C",
    manufacturer: "Cipla",
    price: 95,
    stock: 140,
    lowStockThreshold: 20,
    batchNo: "AB2401",
    expiryDate: expiryAfterMonths(18),
  },
  {
    code: "MED-AB-002",
    name: "Azithromycin 500mg Tablet",
    category: "Antibiotics",
    description: "Macrolide antibiotic used in multiple bacterial infections.",
    prescriptionRequired: true,
    uses: "Throat, chest, and skin bacterial infections",
    dosage: "As prescribed, usually once daily",
    sideEffects: "Nausea, abdominal pain, loose stools",
    warnings: "Use only under medical advice",
    storageInstructions: "Store at room temperature",
    manufacturer: "Dr. Reddy's",
    price: 120,
    stock: 130,
    lowStockThreshold: 20,
    batchNo: "AB2402",
    expiryDate: expiryAfterMonths(18),
  },
  {
    code: "MED-AH-001",
    name: "Cetirizine 10mg Tablet",
    category: "Antihistamines",
    description: "Second-generation antihistamine for allergy symptoms.",
    prescriptionRequired: false,
    uses: "Sneezing, runny nose, itching, hives",
    dosage: "1 tablet once daily or as advised",
    sideEffects: "Mild drowsiness, dry mouth",
    warnings: "Use caution while driving if drowsy",
    storageInstructions: "Store in a cool, dry place",
    manufacturer: "Glenmark",
    price: 35,
    stock: 200,
    lowStockThreshold: 25,
    batchNo: "AH2401",
    expiryDate: expiryAfterMonths(30),
  },
  {
    code: "MED-AH-002",
    name: "Loratadine 10mg Tablet",
    category: "Antihistamines",
    description: "Non-sedating antihistamine for allergic rhinitis and urticaria.",
    prescriptionRequired: false,
    uses: "Allergic rhinitis, skin allergies",
    dosage: "1 tablet once daily",
    sideEffects: "Headache, dry mouth",
    warnings: "Consult doctor in severe liver disease",
    storageInstructions: "Keep below 25C",
    manufacturer: "Torrent",
    price: 48,
    stock: 170,
    lowStockThreshold: 20,
    batchNo: "AH2402",
    expiryDate: expiryAfterMonths(26),
  },
  {
    code: "MED-GI-001",
    name: "Omeprazole 20mg Capsule",
    category: "Gastrointestinal",
    description: "Proton pump inhibitor that reduces stomach acid.",
    prescriptionRequired: false,
    uses: "Acidity, reflux, gastritis",
    dosage: "1 capsule before meals, usually before breakfast",
    sideEffects: "Headache, abdominal pain",
    warnings: "Long-term use should be monitored by a doctor",
    storageInstructions: "Protect from moisture and heat",
    manufacturer: "Lupin",
    price: 60,
    stock: 190,
    lowStockThreshold: 25,
    batchNo: "GI2401",
    expiryDate: expiryAfterMonths(24),
  },
  {
    code: "MED-GI-002",
    name: "Pantoprazole 40mg Tablet",
    category: "Gastrointestinal",
    description: "Proton pump inhibitor for acid-peptic disorders.",
    prescriptionRequired: true,
    uses: "GERD, gastritis, ulcer disease",
    dosage: "1 tablet before food as prescribed",
    sideEffects: "Headache, nausea, bloating",
    warnings: "Use under physician guidance for prolonged duration",
    storageInstructions: "Store below 25C",
    manufacturer: "Intas",
    price: 85,
    stock: 160,
    lowStockThreshold: 20,
    batchNo: "GI2402",
    expiryDate: expiryAfterMonths(22),
  },
  {
    code: "MED-DB-001",
    name: "Metformin 500mg Tablet",
    category: "Diabetes Care",
    description: "First-line oral antidiabetic medicine for type 2 diabetes.",
    prescriptionRequired: true,
    uses: "Blood glucose control in type 2 diabetes",
    dosage: "As prescribed, usually with meals",
    sideEffects: "Nausea, diarrhea, metallic taste",
    warnings: "Use with caution in kidney impairment",
    storageInstructions: "Store in a cool, dry place",
    manufacturer: "USV",
    price: 55,
    stock: 210,
    lowStockThreshold: 30,
    batchNo: "DB2401",
    expiryDate: expiryAfterMonths(28),
  },
  {
    code: "MED-DB-002",
    name: "Glimepiride 2mg Tablet",
    category: "Diabetes Care",
    description: "Sulfonylurea medicine used in type 2 diabetes management.",
    prescriptionRequired: true,
    uses: "Type 2 diabetes blood sugar control",
    dosage: "As prescribed, usually once daily with breakfast",
    sideEffects: "Hypoglycemia, dizziness",
    warnings: "Monitor blood sugar regularly",
    storageInstructions: "Store below 25C",
    manufacturer: "Sanofi",
    price: 70,
    stock: 150,
    lowStockThreshold: 20,
    batchNo: "DB2402",
    expiryDate: expiryAfterMonths(24),
  },
  {
    code: "MED-CV-001",
    name: "Amlodipine 5mg Tablet",
    category: "Cardiovascular",
    description: "Calcium channel blocker used for hypertension and angina.",
    prescriptionRequired: true,
    uses: "High blood pressure, angina",
    dosage: "As prescribed, once daily",
    sideEffects: "Ankle swelling, flushing, dizziness",
    warnings: "Do not stop abruptly without medical advice",
    storageInstructions: "Store in original packaging",
    manufacturer: "Pfizer",
    price: 68,
    stock: 175,
    lowStockThreshold: 20,
    batchNo: "CV2401",
    expiryDate: expiryAfterMonths(24),
  },
  {
    code: "MED-CV-002",
    name: "Atorvastatin 10mg Tablet",
    category: "Cardiovascular",
    description: "Statin medicine to reduce cholesterol levels.",
    prescriptionRequired: true,
    uses: "High cholesterol, cardiovascular risk reduction",
    dosage: "As prescribed, usually once daily",
    sideEffects: "Muscle pain, mild stomach upset",
    warnings: "Periodic liver function monitoring may be required",
    storageInstructions: "Store below 25C and away from light",
    manufacturer: "Zydus",
    price: 95,
    stock: 165,
    lowStockThreshold: 20,
    batchNo: "CV2402",
    expiryDate: expiryAfterMonths(30),
  },
  {
    code: "MED-RS-001",
    name: "Salbutamol Inhaler 100mcg",
    category: "Respiratory",
    description: "Short-acting bronchodilator inhaler for quick relief.",
    prescriptionRequired: true,
    uses: "Asthma and bronchospasm symptom relief",
    dosage: "Use as directed by physician",
    sideEffects: "Tremor, palpitations, headache",
    warnings: "Use inhalation technique correctly",
    storageInstructions: "Keep away from direct heat and sunlight",
    manufacturer: "Cipla",
    price: 210,
    stock: 90,
    lowStockThreshold: 15,
    batchNo: "RS2401",
    expiryDate: expiryAfterMonths(20),
  },
  {
    code: "MED-RS-002",
    name: "Montelukast 10mg Tablet",
    category: "Respiratory",
    description: "Leukotriene receptor antagonist used in asthma and allergic rhinitis.",
    prescriptionRequired: true,
    uses: "Asthma prevention, allergic rhinitis",
    dosage: "1 tablet daily, typically in the evening",
    sideEffects: "Headache, abdominal discomfort",
    warnings: "Use with medical supervision",
    storageInstructions: "Store at room temperature",
    manufacturer: "Sun Pharma",
    price: 125,
    stock: 135,
    lowStockThreshold: 20,
    batchNo: "RS2402",
    expiryDate: expiryAfterMonths(24),
  },
  {
    code: "MED-DM-001",
    name: "Clotrimazole 1% Cream",
    category: "Dermatology",
    description: "Topical antifungal cream for skin fungal infections.",
    prescriptionRequired: false,
    uses: "Ringworm, athlete's foot, fungal skin rash",
    dosage: "Apply thin layer 2-3 times daily as directed",
    sideEffects: "Mild local irritation",
    warnings: "For external use only; avoid contact with eyes",
    storageInstructions: "Store below 25C",
    manufacturer: "Glenmark",
    price: 78,
    stock: 120,
    lowStockThreshold: 15,
    batchNo: "DM2401",
    expiryDate: expiryAfterMonths(22),
  },
  {
    code: "MED-DM-002",
    name: "Hydrocortisone 1% Cream",
    category: "Dermatology",
    description: "Low-potency topical corticosteroid for inflammatory skin conditions.",
    prescriptionRequired: true,
    uses: "Eczema, dermatitis, itching",
    dosage: "Apply a thin layer as advised by physician",
    sideEffects: "Local burning, dryness",
    warnings: "Do not use on infected skin unless advised",
    storageInstructions: "Store in a cool place",
    manufacturer: "Abbott",
    price: 92,
    stock: 95,
    lowStockThreshold: 12,
    batchNo: "DM2402",
    expiryDate: expiryAfterMonths(20),
  },
  {
    code: "MED-SP-001",
    name: "Vitamin D3 60000 IU Softgel",
    category: "Supplements",
    description: "Cholecalciferol supplement for vitamin D deficiency.",
    prescriptionRequired: false,
    uses: "Vitamin D supplementation and bone health",
    dosage: "As advised by doctor, often weekly",
    sideEffects: "Nausea (rare in usual doses)",
    warnings: "Avoid excessive use without monitoring",
    storageInstructions: "Store below 25C in dry conditions",
    manufacturer: "Mankind",
    price: 110,
    stock: 160,
    lowStockThreshold: 20,
    batchNo: "SP2401",
    expiryDate: expiryAfterMonths(30),
  },
  {
    code: "MED-SP-002",
    name: "Ferrous Sulfate 325mg Tablet",
    category: "Supplements",
    description: "Iron supplement used for iron deficiency anemia.",
    prescriptionRequired: false,
    uses: "Prevention and treatment of iron deficiency",
    dosage: "As directed, preferably after meals",
    sideEffects: "Constipation, dark stools, nausea",
    warnings: "Keep out of reach of children",
    storageInstructions: "Store in a dry place",
    manufacturer: "Cipla",
    price: 65,
    stock: 145,
    lowStockThreshold: 18,
    batchNo: "SP2402",
    expiryDate: expiryAfterMonths(26),
  },
  {
    code: "MED-NE-001",
    name: "Gabapentin 300mg Capsule",
    category: "Neurology",
    description: "Anticonvulsant used for neuropathic pain and seizure disorders.",
    prescriptionRequired: true,
    uses: "Neuropathic pain, partial seizures",
    dosage: "Use strictly as prescribed",
    sideEffects: "Drowsiness, dizziness, fatigue",
    warnings: "Do not stop abruptly",
    storageInstructions: "Store at room temperature",
    manufacturer: "Intas",
    price: 155,
    stock: 85,
    lowStockThreshold: 12,
    batchNo: "NE2401",
    expiryDate: expiryAfterMonths(20),
  },
  {
    code: "MED-NE-002",
    name: "Levetiracetam 500mg Tablet",
    category: "Neurology",
    description: "Antiepileptic medicine for seizure control.",
    prescriptionRequired: true,
    uses: "Epilepsy and seizure disorders",
    dosage: "As prescribed by neurologist",
    sideEffects: "Sleepiness, irritability, dizziness",
    warnings: "Dose changes only under medical supervision",
    storageInstructions: "Store in a cool, dry place",
    manufacturer: "Dr. Reddy's",
    price: 190,
    stock: 90,
    lowStockThreshold: 12,
    batchNo: "NE2402",
    expiryDate: expiryAfterMonths(24),
  },
];

async function seedMedicines() {
  if (!process.env.MONGO_URI) {
    throw new Error("MONGO_URI is missing in inventory-service/.env");
  }

  await mongoose.connect(process.env.MONGO_URI, {
    serverSelectionTimeoutMS: 10000,
  });

  const operations = medicines.map((item) => ({
    updateOne: {
      filter: { code: item.code },
      update: {
        $set: {
          code: item.code,
          name: item.name,
          description: item.description,
          prescriptionRequired: item.prescriptionRequired,
          uses: item.uses,
          dosage: item.dosage,
          sideEffects: item.sideEffects,
          warnings: item.warnings,
          storageInstructions: item.storageInstructions,
          category: item.category,
          manufacturer: item.manufacturer,
          imageData: "",
          price: item.price,
          stock: item.stock,
          reservedStock: 0,
          lowStockThreshold: item.lowStockThreshold,
          expiryDate: item.expiryDate,
          batchNo: item.batchNo,
          isActive: true,
          reservations: [],
          batches: [
            {
              batchNo: item.batchNo,
              expiryDate: item.expiryDate,
              stock: item.stock,
              reservedStock: 0,
              reservations: [],
              createdAt: new Date(),
            },
          ],
        },
      },
      upsert: true,
    },
  }));

  const result = await Medicine.collection.bulkWrite(operations, { ordered: true });

  const categoryCounts = medicines.reduce((acc, item) => {
    acc[item.category] = (acc[item.category] || 0) + 1;
    return acc;
  }, {});

  console.log("Seed complete.");
  console.log(`Total medicines in seed set: ${medicines.length}`);
  console.log(`Inserted: ${result.upsertedCount || 0}`);
  console.log(`Updated: ${result.modifiedCount || 0}`);
  console.log("Per-category counts:");
  Object.keys(categoryCounts)
    .sort()
    .forEach((category) => {
      console.log(`- ${category}: ${categoryCounts[category]}`);
    });
}

seedMedicines()
  .catch((error) => {
    console.error("Failed to seed medicines:", error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.connection.close();
  });
